// Auto-generated: static require map for the bundled card artwork
// (public-domain Vector Playing Cards).
/* eslint-disable */
export const CARD_ASPECT = 726 / 500; // height / width of the artwork

export const CARD_IMAGES = {
  '♠': {
    'A': require('../../../assets/cards/ace_of_spades.png'),
    'J': require('../../../assets/cards/jack_of_spades.png'),
    'Q': require('../../../assets/cards/queen_of_spades.png'),
    'K': require('../../../assets/cards/king_of_spades.png'),
    '2': require('../../../assets/cards/2_of_spades.png'),
    '3': require('../../../assets/cards/3_of_spades.png'),
    '4': require('../../../assets/cards/4_of_spades.png'),
    '5': require('../../../assets/cards/5_of_spades.png'),
    '6': require('../../../assets/cards/6_of_spades.png'),
    '7': require('../../../assets/cards/7_of_spades.png'),
    '8': require('../../../assets/cards/8_of_spades.png'),
    '9': require('../../../assets/cards/9_of_spades.png'),
    '10': require('../../../assets/cards/10_of_spades.png'),
  },
  '♥': {
    'A': require('../../../assets/cards/ace_of_hearts.png'),
    'J': require('../../../assets/cards/jack_of_hearts.png'),
    'Q': require('../../../assets/cards/queen_of_hearts.png'),
    'K': require('../../../assets/cards/king_of_hearts.png'),
    '2': require('../../../assets/cards/2_of_hearts.png'),
    '3': require('../../../assets/cards/3_of_hearts.png'),
    '4': require('../../../assets/cards/4_of_hearts.png'),
    '5': require('../../../assets/cards/5_of_hearts.png'),
    '6': require('../../../assets/cards/6_of_hearts.png'),
    '7': require('../../../assets/cards/7_of_hearts.png'),
    '8': require('../../../assets/cards/8_of_hearts.png'),
    '9': require('../../../assets/cards/9_of_hearts.png'),
    '10': require('../../../assets/cards/10_of_hearts.png'),
  },
  '♦': {
    'A': require('../../../assets/cards/ace_of_diamonds.png'),
    'J': require('../../../assets/cards/jack_of_diamonds.png'),
    'Q': require('../../../assets/cards/queen_of_diamonds.png'),
    'K': require('../../../assets/cards/king_of_diamonds.png'),
    '2': require('../../../assets/cards/2_of_diamonds.png'),
    '3': require('../../../assets/cards/3_of_diamonds.png'),
    '4': require('../../../assets/cards/4_of_diamonds.png'),
    '5': require('../../../assets/cards/5_of_diamonds.png'),
    '6': require('../../../assets/cards/6_of_diamonds.png'),
    '7': require('../../../assets/cards/7_of_diamonds.png'),
    '8': require('../../../assets/cards/8_of_diamonds.png'),
    '9': require('../../../assets/cards/9_of_diamonds.png'),
    '10': require('../../../assets/cards/10_of_diamonds.png'),
  },
  '♣': {
    'A': require('../../../assets/cards/ace_of_clubs.png'),
    'J': require('../../../assets/cards/jack_of_clubs.png'),
    'Q': require('../../../assets/cards/queen_of_clubs.png'),
    'K': require('../../../assets/cards/king_of_clubs.png'),
    '2': require('../../../assets/cards/2_of_clubs.png'),
    '3': require('../../../assets/cards/3_of_clubs.png'),
    '4': require('../../../assets/cards/4_of_clubs.png'),
    '5': require('../../../assets/cards/5_of_clubs.png'),
    '6': require('../../../assets/cards/6_of_clubs.png'),
    '7': require('../../../assets/cards/7_of_clubs.png'),
    '8': require('../../../assets/cards/8_of_clubs.png'),
    '9': require('../../../assets/cards/9_of_clubs.png'),
    '10': require('../../../assets/cards/10_of_clubs.png'),
  },
};
